#!/usr/bin/env bash

set -eo pipefail

cd build/nodes
# Allow the script to be run from outside the nodes directory.
basedir=$( dirname "$0" )
cd "$basedir"

if [ -z "$JAVA_HOME" ] && which osascript >/dev/null; then
    # use default version of java installed on mac
    /usr/libexec/java_home --exec java -Xms2048m -Xmx2048m -XX:PermSize=1024m -XX:MaxPermSize=1024m -XX:-UseGCOverheadLimit -jar runnodes.jar "$@"
else
    "${JAVA_HOME:+$JAVA_HOME/bin/}java" -Xms2048m -Xmx2048m -XX:PermSize=1024m -XX:MaxPermSize=1024m -XX:-UseGCOverheadLimit -jar runnodes.jar "$@"
fi
